# Use new container based infrastructure
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
language: node_js
node_js:
  - 'stable'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
after_script:
  - jscoverage --no-highlight lib lib-cov
  - JSFMT_COV=1 mocha -R mocha-lcov-reporter -r jscoverage --covinject=true ./tests | coveralls
